language: python
python:
  - "3.7"

install:
  - pip install -r requirements

script: 
  - export BLOG_DEV=NO
  - make clean
  - make html

deploy:
    provider: pages
    verbose: true
    local_dir: "output/"
    token: $GITHUB_TOKEN
    keep_history: true
    target_branch: master
    on:
        branch: develop
